
name: build-supported-platforms
on: [push]

jobs:
  cmake-generate-and-build:
    strategy:
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest
          }
          - {
            name: "Ubuntu 18.04",
            os: ubuntu-18.04
          }
          - {
            name: "MacOS Latest",
            os: macos-latest
          }

    runs-on: ${{matrix.config.os}}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - run: cd build
      - run: cmake -G ..
      - run: cmake --build .