
name: build-supported-platforms
on: [push]

jobs:
  cmake-generate-and-build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest,
            build_type: Release
          }
          - {
            name: "Ubuntu 18.04",
            os: ubuntu-18.04,
            build_type: Release
          }
          - {
            name: "MacOS Latest",
            os: macos-latest,
            build_type: Release
          }

    runs-on: ${{matrix.config.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Boost on Windows
        if: ${{ contains(matrix.config.os, 'windows') }}
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost-windows
        with:
          boost_version: 1.72.0
          toolset: msvc14.2

      - name: Install Boost on Ubuntu
        if: ${{ contains(matrix.config.os, 'ubuntu') }}
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost-ubuntu
        with:
          boost_version: 1.72.0

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.1'

      - name: CMake Generation Step
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}
        env:
            BOOST_ROOT: ${{ join(steps.install-boost-windows.outputs.BOOST_ROOT, steps.install-boost-ubuntu.outputs.BOOST_ROOT) }}

      - name: CMake Build Step
        run: >
          cmake
          --build ${{github.workspace}}/build
          --config ${{matrix.config.build_type}}