
name: build-supported-platforms
on: [push]

jobs:
  cmake-generate-and-build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest,
            build_type: Release,
            boost_toolset: msvc14.2
          }
          - {
            name: "Ubuntu 18.04",
            os: ubuntu-18.04,
            build_type: Release,
            boost_toolset: gcc
          }
          - {
            name: "MacOS Latest",
            os: macos-latest,
            build_type: Release
          }

    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Boost
        if: ${{ !contains(matrix.config.os, 'mac') }}
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          boost_version: 1.72.0
          toolset: ${{ matrix.config.boost_toolset }}

      - name: Set Windows Pathing for Boost
        if: ${{ contains(matrix.config.os, 'win') }}
        run: |
          echo "${{ steps.install-boost.outputs.BOOST_ROOT }}" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install Boost (mac only)
        if: ${{ contains(matrix.config.os, 'mac') }}
        run: brew install boost

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ matrix.config.os }}-QtCahce

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.1'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Print Environment
        run: |
          echo "$env:PATH"

      - name: CMake Generation Step
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}
        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: CMake Build Step
        run: >
          cmake
          --build ${{github.workspace}}/build
          --config ${{matrix.config.build_type}}