
name: build-supported-platforms
on: [push]

jobs:
  cmake-generate-and-build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest,
            build_type: Release
          }
          - {
            name: "Ubuntu 18.04",
            os: ubuntu-18.04,
            build_type: Release
          }
          - {
            name: "MacOS Latest",
            os: macos-latest,
            build_type: Release
          }

    runs-on: ${{matrix.config.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Boost
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          boost_version: 1.72.0

      - name: CMake Generation Step
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}
          -DBOOST_INCLUDEDIR=$BOOST_ROOT/include
          -DBOOST_LIBRARYDIR=$BOOST_ROOT/lib


      - name: CMake Build Step
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}